In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
#Syntax for 2D SLicing 

In [6]:
a[0:4,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [7]:
a[:,0:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [8]:
a[::1,:1:1]

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [9]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [10]:
a[1:3,0:2]

array([[4, 5],
       [8, 9]])

In [11]:
a[1:3,:2]

array([[4, 5],
       [8, 9]])

In [12]:
a[1:3:1,:2:1]

array([[4, 5],
       [8, 9]])

In [13]:
a[1:3:,:2:]

array([[4, 5],
       [8, 9]])

In [14]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
a[1:4,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [16]:
a[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [17]:
a[1::,1::]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [18]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [20]:
a[1:3,0:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a[1:3:1,::1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
a[0:4:2,0:4]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [24]:
a[::2,::1]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [25]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [39]:
a[-2:, -2:]

array([[10, 11],
       [14, 15]])

In [40]:
a[-4:, -3:-1]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [42]:
a[0::3,0::3]

array([[ 0,  3],
       [12, 15]])

In [43]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [44]:
a[0:3,1:,:2]

array([[[ 3,  4],
        [ 6,  7]],

       [[12, 13],
        [15, 16]],

       [[21, 22],
        [24, 25]]])

In [45]:
a[0:2,:1,:2]

array([[[ 0,  1]],

       [[ 9, 10]]])

In [46]:
 a[::,::2,:1]

array([[[ 0],
        [ 6]],

       [[ 9],
        [15]],

       [[18],
        [24]]])

In [47]:
a[::,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])