In [3]:
import numpy as np

In [2]:
a=np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
ind=[0,2,8]

In [5]:
a[ind]

array([0, 2, 8])

In [6]:
#or
a[[0,2,8]]

array([0, 2, 8])

In [7]:
b=[0,2,8]
a[b]

array([0, 2, 8])

In [8]:
#OR
int=[0,2,8]
x=np.array(ind)
print(x,type(x))
a[x]

[0 2 8] <class 'numpy.ndarray'>


array([0, 2, 8])

In [10]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
row=[0,2,1]
col=[1,0,2]

In [12]:
a[row,col]

array([1, 6, 5])

In [13]:
#OR
a[(0,1,2,1,0),[2,1,0,0,1]]

array([2, 4, 6, 3, 1])

In [14]:
a[(0,1,2,1,0),[2,1,0,0,1]][::-1]

array([1, 3, 6, 4, 2])

In [1]:
#3D Slicing

In [5]:
a=np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
a[(0,2),(0,0),(1,0)]

array([ 1, 18])

In [8]:
a[(0,0,0,1,1,1,2,2,2),(0,1,2,0,1,2,0,1,2),(0,1,2,0,1,2,0,1,2)]

array([ 0,  4,  8,  9, 13, 17, 18, 22, 26])