In [1]:
import numpy as np

In [2]:
a=np.arange(10)
print(a,type(a))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Size :",a.size)
print("Data type :",a.dtype)

Dimension : 1
Shape : (10,)
Size : 10
Data type : int64


In [6]:
a.shape=(5,2)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Size :",a.size)
print("Data type :",a.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (5, 2)
Size : 10
Data type : int64


In [10]:
a=a.reshape(2,5)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Size :",a.size)
print("Data type :",a.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (2, 5)
Size : 10
Data type : int64


In [13]:
a=np.arange(10,22)
print(a,type(a))
len(a)

[10 11 12 13 14 15 16 17 18 19 20 21] <class 'numpy.ndarray'>


12

In [14]:
a.shape=(2,2,3)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Size :",a.size)
print("Data type :",a.dtype)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (2, 2, 3)
Size : 12
Data type : int64


In [17]:
a=np.arange(10,30).reshape(2,5,2)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Size :",a.size)
print("Data type :",a.dtype)

[[[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (2, 5, 2)
Size : 20
Data type : int64
