In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40])
print(a,type(a))

[10 20 30 40] <class 'numpy.ndarray'>


In [3]:
b=a.copy()
print("Origancal Array ={} and {}".format(a,type(a)) )
print("Copied Array ={} and {}".format(b,type(b)) )

Origancal Array =[10 20 30 40] and <class 'numpy.ndarray'>
Copied Array =[10 20 30 40] and <class 'numpy.ndarray'>


In [4]:
print(a[0])
print(a[0])

10
10


In [6]:
a[0]=100 #Modified Original array
print("Origancal Array ={} and {}".format(a,type(a)) )
print("Copied Array ={} and {}".format(b,type(b)) )

Origancal Array =[100  20  30  40] and <class 'numpy.ndarray'>
Copied Array =[10 20 30 40] and <class 'numpy.ndarray'>


In [7]:
b[0]=200 #Modified Copy array
print("Origancal Array ={} and {}".format(a,type(a)) )
print("Copied Array ={} and {}".format(b,type(b)) )

Origancal Array =[100  20  30  40] and <class 'numpy.ndarray'>
Copied Array =[200  20  30  40] and <class 'numpy.ndarray'>


In [8]:
#view()

In [9]:
a=np.array([10,20,30,40])
print(a,type(a))

[10 20 30 40] <class 'numpy.ndarray'>


In [10]:
b=a.view()
print("Origancal Array ={} and {}".format(a,type(a)) )
print("View Array ={} and {}".format(b,type(b)) )

Origancal Array =[10 20 30 40] and <class 'numpy.ndarray'>
View Array =[10 20 30 40] and <class 'numpy.ndarray'>


In [11]:
print(a[0])
print(a[0])

10
10


In [12]:
a[0]=125 #Modified Original array
print("Origancal Array ={} and {}".format(a,type(a)) )
print("Copied Array ={} and {}".format(b,type(b)) )

Origancal Array =[125  20  30  40] and <class 'numpy.ndarray'>
Copied Array =[125  20  30  40] and <class 'numpy.ndarray'>


In [13]:
b[-1]=400 #Modified Original array
print("Origancal Array ={} and {}".format(a,type(a)) )
print("Copied Array ={} and {}".format(b,type(b)) )

Origancal Array =[125  20  30 400] and <class 'numpy.ndarray'>
Copied Array =[125  20  30 400] and <class 'numpy.ndarray'>


In [15]:
print("a={} addr of a ={}".format(a,id(a)))
print("b={} addr of a ={}".format(b,id(b)))

a=[125  20  30 400] addr of a =2587599358832
b=[125  20  30 400] addr of a =2587599358352


In [16]:
a=np.array([10,20,30,40])
b=a.copy()
print(a,a.base)
print(b,b.base)

[10 20 30 40] <class 'numpy.ndarray'>
[10 20 30 40] None
[10 20 30 40] None


In [17]:
a=np.array([10,20,30,40])
b=a.view()
print(a,a.base)
print(b,b.base)

[10 20 30 40] None
[10 20 30 40] [10 20 30 40]
