In [1]:
import numpy as np

In [2]:
arr1=np.array([10,30,50,60,80,60])
newarr=np.diff(arr1)
print(newarr)

[ 20  20  10  20 -20]


In [4]:
arr1=np.array([10,30,50,60,80,60])
newarr=np.diff(arr1,n=2)
print(newarr)

[  0 -10  10 -40]


In [3]:
arr1=np.array([1,2,3,4,5])
newarr=np.diff(arr1, n=2)
print(newarr)

[0 0 0]
