In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,50,60])
print(a)
print("Using for Loop")
for val in a:
    print(val)
print("Using while Loop")
i=0
while(i<len(a)):
    print(a[i])
    i=i+1
print("Using while Loop")
i=0
while(i<len(a)):
    print(a[i],end="-->")
    i=i+1

[10 20 30 40 50 60]
Using for Loop
10
20
30
40
50
60
Using while Loop
10
20
30
40
50
60
Using while Loop
10-->20-->30-->40-->50-->60-->

In [3]:
a=np.arange(16).reshape(4,4)
print("Contant of a\n",a)
print("Dimension =",a.ndim)
print("Shape =",a.shape)

Contant of a
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimension = 2
Shape = (4, 4)


In [4]:
for val in a:
    for inr in val:
        print(inr)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [5]:
a=np.arange(16).reshape(2,4,2)
print("Contant of a\n",a)
print("Dimension =",a.ndim)
print("Shape =",a.shape)

Contant of a
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
Dimension = 3
Shape = (2, 4, 2)


In [6]:
for val in a:
    for inr in val:
        for dinr in inr:
            print(dinr)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [7]:
# Iteration Using NumPy Model


In [8]:
a=np.arange(5)
print(a,type(a))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [9]:
for val in np.nditer(a):
    print(val)

0
1
2
3
4


In [10]:
for index,value in np.ndenumerate(a):
    print(index,"-->",value)

(0,) --> 0
(1,) --> 1
(2,) --> 2
(3,) --> 3
(4,) --> 4


In [11]:
a=np.arange(9).reshape(3,3)
print(a,type(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [12]:
for val in np.nditer(a):
    print(val)

0
1
2
3
4
5
6
7
8


In [13]:
for index,value in np.ndenumerate(a):
    print(index,"-->",value)

(0, 0) --> 0
(0, 1) --> 1
(0, 2) --> 2
(1, 0) --> 3
(1, 1) --> 4
(1, 2) --> 5
(2, 0) --> 6
(2, 1) --> 7
(2, 2) --> 8


In [14]:
a=np.arange(16).reshape(2,4,2)
print(a,type(a))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]] <class 'numpy.ndarray'>


In [15]:
for val in np.nditer(a):
    print(val)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [16]:
for index,value in np.ndenumerate(a):
    print(index,"-->",value)

(0, 0, 0) --> 0
(0, 0, 1) --> 1
(0, 1, 0) --> 2
(0, 1, 1) --> 3
(0, 2, 0) --> 4
(0, 2, 1) --> 5
(0, 3, 0) --> 6
(0, 3, 1) --> 7
(1, 0, 0) --> 8
(1, 0, 1) --> 9
(1, 1, 0) --> 10
(1, 1, 1) --> 11
(1, 2, 0) --> 12
(1, 2, 1) --> 13
(1, 3, 0) --> 14
(1, 3, 1) --> 15
