In [4]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.add(arr1, arr2)
print(newarr)

[2 4 6]


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

12


In [7]:
a=np.arange(3*3).reshape(3,3)
b=np.array([[1,0,0],[0,1,0],[0,0,1]])
print("Matrix A \n",a)
print("Matrix B \n",b)

Matrix A 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix B 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
c=np.add(a,b)
print("Matrix c \n",c)

Matrix c 
 [[1 1 2]
 [3 5 5]
 [6 7 9]]


In [14]:
e=np.sum([a,b])
print("Matrix D \n",e)

Matrix D 
 39


In [9]:
d=np.sum((a,b),axis=1)
print("Matrix D \n",d)

Matrix D 
 [[ 9 12 15]
 [ 1  1  1]]


In [10]:
d=np.sum(np.sum((a,b),axis=1),axis=1)
print("Matrix D \n",d)

Matrix D 
 [36  3]


In [12]:
d=np.sum(np.sum(np.sum((a,b),axis=1),axis=1),axis=0)
print("Matrix D \n",d)

Matrix D 
 39


In [18]:
arr1 = np.array([1, 2, 3,4])
newarr = np.cumsum(arr1)
print(newarr)

[ 1  3  6 10]


In [19]:
arr1 = np.array([1, 2, 3,4])
newarr = np.cumsum(arr1,n=3)
print(newarr)

TypeError: cumsum() got an unexpected keyword argument 'n'