In [1]:
import numpy as np

In [2]:
a=np.array(list("MISSISSIPPI"))
print(a)

['M' 'I' 'S' 'S' 'I' 'S' 'S' 'I' 'P' 'P' 'I']


In [3]:
ind=np.where(a=="s")
print(ind)

(array([], dtype=int64),)


In [4]:
ind=np.where(a=="S")
print(ind)

(array([2, 3, 5, 6]),)


In [5]:
ind=np.where(a=="P")
print(ind)

(array([8, 9]),)


In [6]:
ind=np.where(a=="K")
print(ind)

(array([], dtype=int64),)


In [8]:
a=np.array([[10,20,30],[20,10,40],[10,50,60]])
print(a,type(a))

[[10 20 30]
 [20 10 40]
 [10 50 60]] <class 'numpy.ndarray'>


In [9]:
ind=np.where(a==10)
print(ind)

(array([0, 1, 2]), array([0, 1, 0]))


In [10]:
a=np.random.randint(0,11 ,size=(4,4,4))
print(a)

[[[ 3  9  9  9]
  [ 5  8 10  3]
  [ 1  4  0  9]
  [ 4  5 10  7]]

 [[ 9  7  4  7]
  [ 3  7  8  1]
  [ 5  5  5 10]
  [ 0  7 10  2]]

 [[ 7  0  6  8]
  [10  2  4  0]
  [10  3 10  3]
  [ 9  8  3 10]]

 [[ 1  5  9  3]
  [ 0  8  5  0]
  [ 8 10  7 10]
  [ 5  4 10  7]]]


In [11]:
ind=np.where(a==5)
print(ind)

(array([0, 0, 1, 1, 1, 3, 3, 3]), array([1, 3, 2, 2, 2, 0, 1, 3]), array([0, 1, 0, 1, 2, 1, 2, 0]))


In [12]:
ind=np.where(a==10)
print(ind)

(array([0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3]), array([1, 3, 2, 3, 1, 2, 2, 3, 2, 2, 3]), array([2, 2, 3, 2, 0, 0, 2, 3, 1, 3, 2]))


In [13]:
# Find Even Indices of multiplr of 3
ind=np.where(a%3==0)
print(ind)

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 0, 0, 1, 2, 2, 0, 1, 3, 0, 0, 1, 2, 2, 3, 3, 0, 0, 1, 1]), array([0, 1, 2, 3, 3, 2, 3, 0, 0, 0, 1, 2, 3, 1, 3, 0, 2, 2, 3, 0, 3]))


In [17]:
ind=np.where(a%2!=1)
print(a)
print(ind)

[[[ 3  9  9  9]
  [ 5  8 10  3]
  [ 1  4  0  9]
  [ 4  5 10  7]]

 [[ 9  7  4  7]
  [ 3  7  8  1]
  [ 5  5  5 10]
  [ 0  7 10  2]]

 [[ 7  0  6  8]
  [10  2  4  0]
  [10  3 10  3]
  [ 9  8  3 10]]

 [[ 1  5  9  3]
  [ 0  8  5  0]
  [ 8 10  7 10]
  [ 5  4 10  7]]]
(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3]), array([1, 1, 2, 2, 3, 3, 0, 1, 2, 3, 3, 3, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3,
       3, 1, 1, 1, 2, 2, 2, 3, 3]), array([1, 2, 1, 2, 0, 2, 2, 2, 3, 0, 2, 3, 1, 2, 3, 0, 1, 2, 3, 0, 2, 1,
       3, 0, 1, 3, 0, 1, 3, 1, 2]))
