In [2]:
import numpy as np

In [5]:
a=np.arange(12).reshape(4,3)
print(a,"\n",a.ndim,"\n",a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)


In [9]:
a.shape=(12,)
print(a,"\n",a.ndim,"\n",a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 1 
 (12,)


In [10]:
# We are Using flatten()
a=np.arange(12).reshape(4,3)
print(a,"\n",a.ndim,"\n",a.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)


In [11]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
print("dimantion of a=",a.ndim)
print("Shape of a=",a.shape)

dimantion of a= 2
Shape of a= (4, 3)


In [16]:
x=a.flatten()
print(x)
print("dimantion of x=",x.ndim)
print("Shape of x=",x.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimantion of x= 1
Shape of x= (12,)


In [18]:
# We are Using flatten()
a=np.arange(12).reshape(4,3)
print("Given Array \n",a,"\n",a.ndim,"\n",a.shape)
print("-"*50)
x=a.flatten()
print(x)
print("dimantion of x=",x.ndim)
print("Shape of x=",x.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimantion of x= 1
Shape of x= (12,)


In [19]:
# We are Using flatten()
a=np.arange(12).reshape(4,3)
print("Given Array \n",a,"\n",a.ndim,"\n",a.shape)
print("-"*50)
x=a.flatten("c")
print(x)
print("dimantion of x=",x.ndim)
print("Shape of x=",x.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimantion of x= 1
Shape of x= (12,)


In [25]:
# We are Using flatten()
a=np.arange(12).reshape(4,3)
print("Given Array \n",a,"\n",id(a))
print("-"*50)
x=a.flatten("f")
print(x,"\t",id(x))
print("dimantion of x=",x.ndim)
print("Shape of x=",x.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 1781338555856
--------------------------------------------------
[ 0  3  6  9  1  4  7 10  2  5  8 11] 	 1781338088304
dimantion of x= 1
Shape of x= (12,)


In [21]:
# We are Using ravel()
a=np.arange(12).reshape(4,3)
print("Given Array \n",a,"\n",a.ndim,"\n",a.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)


In [22]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
print("Given Array \n",a,"\n",a.ndim,"\n",a.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 2 
 (4, 3)


In [26]:
x=a.ravel()
print(x,type(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>


In [32]:
# We are Using flatten()
a=np.arange(12).reshape(4,3)
print("Given Array \n",a)
print("-"*50)
x=a.ravel()
print(x)
print("dimantion of x=",x.ndim)
print("Shape of x=",x.shape)

Given Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimantion of x= 1
Shape of x= (12,)


In [35]:
# Differances B/w flatten() and Ravel()
a=np.arange(12).reshape(4,3)
print("Orignal Array \n",a)
print("-"*50)
print("Flatten Array")
flt=a.flatten()
flt[0]=10
print(flt)
print("-"*50)
print("Orignal Array \n",a)
print("-"*50)
print("Ravel Array")
rav=a.ravel()
rav[0]=20
print(rav)
print("-"*50)
print("Orignal Array \n",a)

Orignal Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------------------------------------
Flatten Array
[10  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------
Orignal Array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
--------------------------------------------------
Ravel Array
[20  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------
Orignal Array 
 [[20  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
