In [2]:
import numpy as np

In [6]:
a=np.random.rand(1,2)
print(a)

[[0.37157053 0.4601451 ]]


In [8]:
a=np.array([10,20,30,40])
b=np.array([100,200,300,400])
c=np.hstack((a,b))
print(c,type(c))

[ 10  20  30  40 100 200 300 400] <class 'numpy.ndarray'>


In [14]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[100,200],[300,400],[500,600]])
print("Matrix -A")
print(a,type(a),a.shape)
print("="*50)
print("Matrix -B")
print(b,type(b),b.shape)
print("="*50)
c=np.hstack((a,b))
print("Matrix -c")
print(c,type(c),c.shape)

Matrix -A
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'> (3, 3)
Matrix -B
[[100 200]
 [300 400]
 [500 600]] <class 'numpy.ndarray'> (3, 2)
Matrix -c
[[ 10  20  30 100 200]
 [ 40  50  60 300 400]
 [ 70  80  90 500 600]] <class 'numpy.ndarray'> (3, 5)


In [15]:
a=np.array([10,20,30,40])
b=np.array([100,200,300,400])
c=np.vstack((a,b))
print(c,type(c))

[[ 10  20  30  40]
 [100 200 300 400]] <class 'numpy.ndarray'>


In [16]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[100,200],[300,400],[500,600]])
print("Matrix -A")
print(a,type(a),a.shape)
print("="*50)
print("Matrix -B")
print(b,type(b),b.shape)
print("="*50)
c=np.vstack((a,b))
print("Matrix Vstack-C")
print(c,type(c),c.shape)

Matrix -A
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'> (3, 3)
Matrix -B
[[100 200]
 [300 400]
 [500 600]] <class 'numpy.ndarray'> (3, 2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [17]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[100,200,700],[300,400,800],[500,600,900]])
print("Matrix -A")
print(a,type(a),a.shape)
print("="*50)
print("Matrix -B")
print(b,type(b),b.shape)
print("="*50)
c=np.vstack((a,b))
print("Matrix Vstack-C")
print(c,type(c),c.shape)

Matrix -A
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'> (3, 3)
Matrix -B
[[100 200 700]
 [300 400 800]
 [500 600 900]] <class 'numpy.ndarray'> (3, 3)
Matrix Vstack-C
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 200 700]
 [300 400 800]
 [500 600 900]] <class 'numpy.ndarray'> (6, 3)


In [18]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[100,200,700],[300,400,800]])
print("Matrix -A")
print(a,type(a),a.shape)
print("="*50)
print("Matrix -B")
print(b,type(b),b.shape)
print("="*50)
c=np.vstack((a,b))
print("Matrix Vstack-C")
print(c,type(c),c.shape)

Matrix -A
[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'> (3, 3)
Matrix -B
[[100 200 700]
 [300 400 800]] <class 'numpy.ndarray'> (2, 3)
Matrix Vstack-C
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 200 700]
 [300 400 800]] <class 'numpy.ndarray'> (5, 3)


In [19]:
a=np.array([[10],[20],[30]])
b=np.array([[100],[200],[300]])
print("Matrix -A")
print(a,type(a),a.shape)
print("="*50)
print("Matrix -B")
print(b,type(b),b.shape)

Matrix -A
[[10]
 [20]
 [30]] <class 'numpy.ndarray'> (3, 1)
Matrix -B
[[100]
 [200]
 [300]] <class 'numpy.ndarray'> (3, 1)


In [21]:
d=np.dstack((a,b))
print(d,type(d),d.shape)

[[[ 10 100]]

 [[ 20 200]]

 [[ 30 300]]] <class 'numpy.ndarray'> (3, 1, 2)


In [24]:
h=np.hstack((a,b))
print(h,type(h),h.shape)

[[ 10 100]
 [ 20 200]
 [ 30 300]] <class 'numpy.ndarray'> (3, 2)


In [23]:
v=np.vstack((a,b))
print(v,type(v),v.shape)

[[ 10]
 [ 20]
 [ 30]
 [100]
 [200]
 [300]] <class 'numpy.ndarray'> (6, 1)
