In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [3]:
a[1]

np.int64(20)

In [4]:
a[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [5]:
a[4]

np.int64(50)

In [6]:
len(a)

5

In [7]:
a[len(a)-2]

np.int64(40)

In [8]:
a[-2]

np.int64(40)

In [9]:
a[-1]

np.int64(50)

In [10]:
print(a[-1])

50


In [12]:
a=np.arange(16).reshape(4,4)
print(a,type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] <class 'numpy.ndarray'>


In [13]:
a[1,2]

np.int64(6)

In [14]:
a[1]

array([4, 5, 6, 7])

In [23]:
a[-4][3]

np.int64(3)

In [22]:
a[3][3]

np.int64(15)

In [24]:
a[-1,-4]

np.int64(12)

In [26]:
a=np.arange(27).reshape(3,3,3)
print(a,type(a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


In [27]:
a[1,1,1]

np.int64(13)

In [28]:
a[-1][-2][2]

np.int64(23)

In [29]:
a[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])