In [1]:
import numpy as np

In [2]:
# Consider the Following Liner Equation
# 2x+3y=6
# 6x+4y=3
# find x and Y values

In [3]:
a=np.array([[2,3],[6,4]])
b=np.array([6,3])
print(a,type(a))
print(b,type(b))

[[2 3]
 [6 4]] <class 'numpy.ndarray'>
[6 3] <class 'numpy.ndarray'>


In [5]:
# SOlve
sol=np.linalg.solve(a,b)
print(sol)

[-1.5  3. ]


In [7]:
a=np.array([[2,3],[6,4]])
b=np.array([6,2])
print(a,type(a))
print(b,type(b))
# SOlve
sol=np.linalg.solve(a,b)
print(sol)

[[2 3]
 [6 4]] <class 'numpy.ndarray'>
[6 2] <class 'numpy.ndarray'>
[-1.8  3.2]


In [11]:
# Consider
# x+y+z=6
# 2x+3y+9z=16
# 2x-4y-9z=20
a=np.array([[1,1,1],[2,3,9],[2,-4,-9]])
b=np.array([6,16,20])
print(a,"\n",b)

[[ 1  1  1]
 [ 2  3  9]
 [ 2 -4 -9]] 
 [ 6 16 20]


In [12]:
# Solve

In [13]:
sol=np.linalg.solve(a,b)
print(sol)

[ 8.19354839 -3.22580645  1.03225806]


In [15]:
# Consider
# x+y+z=6
# 2x+3y+9z=16
# 2x-4y-9z=20
a=np.array([[1,1,1],[2,3,9],[2,-4,-9]])
b=np.array([6,16,20])
print(a,"\n",b)
 # Solve
sol=np.linalg.solve(a,b)
print("Value of x=",sol[0])
print("Value of y=",sol[1])
print("Value of z=",sol[2])

[[ 1  1  1]
 [ 2  3  9]
 [ 2 -4 -9]] 
 [ 6 16 20]
Value of x= 8.193548387096774
Value of y= -3.225806451612903
Value of z= 1.032258064516129


In [16]:
# Find Det of Given Matrix
a=np.array([[1,2],[3,4]])
print("Given Matrix\n",a)

Given Matrix
 [[1 2]
 [3 4]]


In [18]:
# solve
deta=np.linalg.det(a)
print("Det of a =",deta)

Det of a = -2.0000000000000004


In [19]:
# Find Det of Given Matrix
a=np.array([[4,3],[1,2]])
print("Given Matrix\n",a)
# solve
deta=np.linalg.det(a)
print("Det of a =",deta)

Given Matrix
 [[4 3]
 [1 2]]
Det of a = 4.999999999999999


In [20]:
# Find Det of Given Matrix
a=np.array([[1,2,3],[4,5,6],[7,8,2]])
print("Given Matrix\n",a)
# solve
deta=np.linalg.det(a)
print("Det of a =",deta)

Given Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 2]]
Det of a = 21.0


In [21]:
# Find Inverse of Given Matrix
a=np.array([[1,2],[3,4]])
print(a)
# Solve
sol=np.linalg.inv(a)
print("Invers Of Matrix A \n",sol)

[[1 2]
 [3 4]]
Invers Of Matrix A 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
# Find Inverse of Given Matrix
a=np.array([[1,2,3],[4,5,6],[7,8,2]])
print("Given Matrix\n",a)
# Solve
sol=np.linalg.inv(a)
print("Invers Of Matrix A \n",sol)

Given Matrix
 [[1 2 3]
 [4 5 6]
 [7 8 2]]
Invers Of Matrix A 
 [[-1.80952381  0.95238095 -0.14285714]
 [ 1.61904762 -0.9047619   0.28571429]
 [-0.14285714  0.28571429 -0.14285714]]
