In [1]:
import numpy as np

In [2]:
a=np.array([[11,20],[30,40]])
b=np.array([[50,60],[1,3]])
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix A \n ", b,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix A 
  [[50 60]
 [ 1  3]] 
 ------------------------------


In [3]:
c=np.add(a,b)
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[50 60]
 [ 1  3]] 
 ------------------------------
Matrix C 
  [[61 80]
 [31 43]] 
 ------------------------------


In [4]:
d=a+c
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)
print("Matrix D \n ", d,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix C 
  [[61 80]
 [31 43]] 
 ------------------------------
Matrix D 
  [[ 72 100]
 [ 61  83]] 
 ------------------------------


In [5]:
a=np.array([[11,20],[30,40]])
b=np.array([[50,60],[1,3]])
c=np.subtract(a,b)
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[50 60]
 [ 1  3]] 
 ------------------------------
Matrix C 
  [[-39 -40]
 [ 29  37]] 
 ------------------------------


In [6]:
a=np.array([[11,20],[30,40]])
b=np.array([[50,60],[1,3]])
c=a-b
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[50 60]
 [ 1  3]] 
 ------------------------------
Matrix C 
  [[-39 -40]
 [ 29  37]] 
 ------------------------------


In [7]:
a=np.array([[11,20],[30,40]])
b=np.array([[50,60],[1,3]])
c=np.multiply(a,b)
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[50 60]
 [ 1  3]] 
 ------------------------------
Matrix C 
  [[ 550 1200]
 [  30  120]] 
 ------------------------------


In [8]:
a=np.array([[11,20],[30,40]])
b=np.array([[50,60],[1,3]])
c=a*b
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[50 60]
 [ 1  3]] 
 ------------------------------
Matrix C 
  [[ 550 1200]
 [  30  120]] 
 ------------------------------


In [9]:
#Dot()
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.dot(a,b)
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[ 71 102]
 [150 220]] 
 ------------------------------


In [10]:
#matmul()


In [11]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.matmul(a,b)
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[ 71 102]
 [150 220]] 
 ------------------------------


In [12]:
# Devide

In [13]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.divide(a,b)  #Elementwise Division
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[11. 10.]
 [10. 10.]] 
 ------------------------------


In [14]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=a/b  #Elementwise Division by using / opertator insted to divide
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[11. 10.]
 [10. 10.]] 
 ------------------------------


In [15]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.floor_divide(a,b)  #Elementwise Division with Integer Quiotent
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[11 10]
 [10 10]] 
 ------------------------------


In [16]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=a//b  #Elementwise floor Division by using // opertator insted to divide
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[11 10]
 [10 10]] 
 ------------------------------


In [17]:
 # Modulo Devision

In [18]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.mod(a,b)  #Elementwise Modulo Division 
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[0 0]
 [0 0]] 
 ------------------------------


In [19]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=a%b  #Elementwise Modulo Division  by using % opertator insted to divide
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[0 0]
 [0 0]] 
 ------------------------------


In [20]:
# Power Value

In [21]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=np.power(a,b)  #Elementwise Exponention OR Power Value
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[     11     400]
 [  27000 2560000]] 
 ------------------------------


In [23]:
a=np.array([[11,20],[30,40]])
b=np.array([[1,2],[3,4]])
c=a**b  #Elementwise Exponention OR Power Value by using ** operator insted by power operation
print("Matrix A \n ", a,"\n","-"*30)
print("Matrix B \n ", b,"\n","-"*30)
print("Matrix C \n ", c,"\n","-"*30)

Matrix A 
  [[11 20]
 [30 40]] 
 ------------------------------
Matrix B 
  [[1 2]
 [3 4]] 
 ------------------------------
Matrix C 
  [[     11     400]
 [  27000 2560000]] 
 ------------------------------
