In [1]:
import numpy as np

In [2]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [3]:
a.shape=(9,)
print(a)

[10 20 30 40 50 60 70 80 90]


In [5]:
#Today Requirement is get multiple of 3 
#Create Boolean Array
b=a%3==0 #Here b is called Boolean Aarray of type ndarray
print(b,type(a))

[False False  True False False  True False False  True] <class 'numpy.ndarray'>


In [7]:
a[b]

array([30, 60, 90])

In [8]:
#get the multiple of 3
a[a%3==0]

array([30, 60, 90])

In [9]:
 #get the multiple of 5
a[a%5==0]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
a=np.array([[20,-60,25],[-89,60,30],[50,90,-36]])
print(a,type(a))

[[ 20 -60  25]
 [-89  60  30]
 [ 50  90 -36]] <class 'numpy.ndarray'>


In [11]:
pa=a[a>0]
print(pa,type(pa))

[20 25 60 30 50 90] <class 'numpy.ndarray'>


In [12]:
a[a<0]

array([-60, -89, -36])

In [13]:
print(a)

[[ 20 -60  25]
 [-89  60  30]
 [ 50  90 -36]]


In [14]:
x=list(filter(lambda n: n>0,a))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()