In [1]:
import numpy as np


In [2]:
# Append

In [3]:
a=np.array([10,20,30])
print(a,type(a))

[10 20 30] <class 'numpy.ndarray'>


In [4]:
np.append(a,100)
print(a)

[10 20 30]


In [5]:
a=np.append(a,100)
print(a,type(a))

[ 10  20  30 100] <class 'numpy.ndarray'>


In [6]:
# Appending Multiple Array

In [7]:
a=np.append(a,[100,200,300,400])
print(a,type(a))

[ 10  20  30 100 100 200 300 400] <class 'numpy.ndarray'>


In [8]:
# 2D
a=np.array([[0,20],[30,40]])
print(a)

[[ 0 20]
 [30 40]]


In [9]:
a=np.append(a,[[50,60]],axis=0)
print(a)

[[ 0 20]
 [30 40]
 [50 60]]


In [10]:
a=np.append(a,[[70],[80],[90]],axis=1)
print(a)

[[ 0 20 70]
 [30 40 80]
 [50 60 90]]


In [11]:
arr=np.arange(1,13).reshape(2,6)
print("Orignal Array \n",arr)

Orignal Array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
# Create Another Array Which is to Appebd column Wise

In [13]:
col=np.arange(5,11).reshape(1,6)
print("Appended Array column wise \n",col)

Appended Array column wise 
 [[ 5  6  7  8  9 10]]


In [14]:
arr_col=np.append(arr,col,axis=0)
print("Array After Appending the values column wise")
print(arr_col)

Array After Appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]]


In [15]:
arr=np.arange(1,3).reshape(2,1)
print("Orignal Array \n",arr)
row=np.arange(3,9).reshape(2,3)
print("Appended Array Row wise \n",row)
arr_row=np.append(arr,row,axis=1)
print("Array After Appending the values Row wise")
print(arr_row)

Orignal Array 
 [[1]
 [2]]
Appended Array Row wise 
 [[3 4 5]
 [6 7 8]]
Array After Appending the values Row wise
[[1 3 4 5]
 [2 6 7 8]]


In [16]:
 a=np.array([[1,0],[0,1]])
print(a)

[[1 0]
 [0 1]]


In [17]:
 a=np.append(a,[[0,0]],axis=0)
print(a)

[[1 0]
 [0 1]
 [0 0]]


In [18]:
 a=np.append(a,[[0],[0],[1]],axis=1)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [19]:
# Insert Operation

In [20]:
a=np.array([10,20,30,40,50])
print(a,type(a))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [21]:
a=np.insert(a,1,15)
print(a,type(a))

[10 15 20 30 40 50] <class 'numpy.ndarray'>


In [22]:
a=np.insert(a,3,[11,33,22,44])
print(a,type(a))

[10 15 20 11 33 22 44 30 40 50] <class 'numpy.ndarray'>


In [23]:
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print(a,type(a))

[[10 20 30]
 [40 50 60]
 [70 80 90]] <class 'numpy.ndarray'>


In [24]:
a=np.insert(a,1,[11,22,33],axis=0)
print(a)

[[10 20 30]
 [11 22 33]
 [40 50 60]
 [70 80 90]]


In [25]:
a=np.insert(a,1,[33,44,55,66],axis=1)
print(a)

[[10 33 20 30]
 [11 44 22 33]
 [40 55 50 60]
 [70 66 80 90]]


In [26]:
# DELETE

In [27]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a,type(a))

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>


In [28]:
a=np.delete(a,1)
print(a)

[10 30 40 50 60 70 80 90]


In [29]:
a=np.delete(a,[0,-2,-1])

In [30]:
print(a)

[30 40 50 60 70]


In [31]:
a=np.arange(5*5).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
a=np.delete(a,2,axis=0)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [33]:
a=np.delete(a,[1,3],axis=0)
print(a)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]


In [34]:
a=np.delete(a,[1,3],axis=1)
print(a)

[[ 0  2  4]
 [15 17 19]]


In [35]:
a=np.delete(a,[0,2],axis=1)
print(a)

[[ 2]
 [17]]


In [48]:
a=np.arange(5*5).reshape(5,5)
print(a)
print(a.shape)
print(a.shape[0])
print(a.shape[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
5
5


In [49]:
a=np.delete(a,[int(i) for i in range(a.shape[0])], axis=1)
print(a)

[]
