In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(4,3)
print("Orignal : \n",a)
a[:,[2,0]]=a[:,[0,2]]
print("After Swapping Column \n",a)

Orignal : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After Swapping Column 
 [[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


In [3]:
a=np.arange(12).reshape(4,3)
print("Orignal : \n",a)
a[[3,0],:]=a[[0,3],:]
print("After Swapping Row \n",a)

Orignal : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After Swapping Row 
 [[ 9 10 11]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  1  2]]
