In [1]:
import numpy as np

In [2]:
# 1D- Array
a=np.array([10,2,13,4,-5,0,16,25,-16])
print(a,type(a))

[ 10   2  13   4  -5   0  16  25 -16] <class 'numpy.ndarray'>


In [5]:
np.sort(a)

array([-16,  -5,   0,   2,   4,  10,  13,  16,  25])

In [6]:
print(a)

[ 10   2  13   4  -5   0  16  25 -16]


In [7]:
np.sort(a)[::-1]

array([ 25,  16,  13,  10,   4,   2,   0,  -5, -16])

In [9]:
# 2D- Array
a=np.array([10,2,13,4,-5,0,16,25,-16]).reshape(3,3)
print(a,type(a))

[[ 10   2  13]
 [  4  -5   0]
 [ 16  25 -16]] <class 'numpy.ndarray'>


In [11]:
np.sort(a)

array([[  2,  10,  13],
       [ -5,   0,   4],
       [-16,  16,  25]])

In [12]:
print(a)

[[ 10   2  13]
 [  4  -5   0]
 [ 16  25 -16]]


In [14]:
np.sort(a,axis=0) #here axiss=0 Represent Column

array([[  4,  -5, -16],
       [ 10,   2,   0],
       [ 16,  25,  13]])

In [15]:
np.sort(a,axis=1) #here axiss=1 Represent Row

array([[  2,  10,  13],
       [ -5,   0,   4],
       [-16,  16,  25]])

In [16]:
np.sort(a,axis=1)[::-1]

array([[-16,  16,  25],
       [ -5,   0,   4],
       [  2,  10,  13]])

In [18]:
a=np.array([10,20,3,4,11,15,16,7,8,-6,0,12]).reshape(2,3,2)
print(a)

[[[10 20]
  [ 3  4]
  [11 15]]

 [[16  7]
  [ 8 -6]
  [ 0 12]]]


In [19]:
np.sort(a)

array([[[10, 20],
        [ 3,  4],
        [11, 15]],

       [[ 7, 16],
        [-6,  8],
        [ 0, 12]]])

In [20]:
np.sort(a,axis=0)

array([[[10,  7],
        [ 3, -6],
        [ 0, 12]],

       [[16, 20],
        [ 8,  4],
        [11, 15]]])

In [21]:
print(a)

[[[10 20]
  [ 3  4]
  [11 15]]

 [[16  7]
  [ 8 -6]
  [ 0 12]]]


In [22]:
np.sort(a,axis=1)

array([[[ 3,  4],
        [10, 15],
        [11, 20]],

       [[ 0, -6],
        [ 8,  7],
        [16, 12]]])

In [23]:
a=np.array([10,20,3,4,11,15,16,7,8,-6,0,12]).reshape(3,4)
print(a)

[[10 20  3  4]
 [11 15 16  7]
 [ 8 -6  0 12]]


In [24]:
a.shape=(12,)
print(a)

[10 20  3  4 11 15 16  7  8 -6  0 12]


In [26]:
np.sort(a).reshape(3,4)

array([[-6,  0,  3,  4],
       [ 7,  8, 10, 11],
       [12, 15, 16, 20]])

In [27]:
np.sort(a)[::-1].reshape(3,4)

array([[20, 16, 15, 12],
       [11, 10,  8,  7],
       [ 4,  3,  0, -6]])

In [28]:
np.sort(a).reshape(2,3,2)

array([[[-6,  0],
        [ 3,  4],
        [ 7,  8]],

       [[10, 11],
        [12, 15],
        [16, 20]]])