In [1]:
import numpy as np

In [2]:
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[3 5 7 7 5 7 5 5 7 5 7 5 7 3 7 7 3 5 5 7 7 7 5 7 7 7 7 5 7 7 7 5 3 7 7 7 5
 7 7 5 7 5 7 7 5 7 7 7 7 7 3 7 5 7 7 7 7 7 7 3 7 7 5 7 7 7 7 5 7 7 7 5 5 7
 7 3 7 7 3 7 5 7 7 7 7 7 7 7 7 5 7 5 7 7 3 5 7 5 7 7]


In [3]:
print(x.size)

100


In [4]:
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(10))
print(x)

[7 7 3 5 7 7 7 5 3 5]


In [5]:
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(3,5))
print(x)

[[5 7 5 7 7]
 [3 7 5 7 7]
 [5 7 5 5 5]]


In [6]:
a=np.array([3,5,7,9])
x=np.random.choice(a,p=[0.1,0.3,0.6,0.0],size=(2,2,2))
print(x)

[[[7 7]
  [7 5]]

 [[3 7]
  [7 3]]]
