In [1]:
import numpy as np

In [2]:
a=np.random.randint(10)
print(a)

8


In [3]:
a=np.random.randint(1000,2000)
print(a)

1777


In [4]:
a=np.random.randint(10,20,size=6)
print(a)

[11 11 17 16 11 18]


In [5]:
a=np.random.randint(10,20,size=6)
print(a)

[18 13 16 15 12 10]


In [6]:
a=np.random.randint(10,20,size=15)
print(a)

[19 16 14 17 14 17 12 18 16 12 13 18 19 19 18]


In [7]:
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

Dimension : 1
Shape : (15,)
Data type : int32
Size : 15


In [8]:
a=np.random.randint(10,20,size=(3,3))
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[14 12 18]
 [11 18 15]
 [12 12 14]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (3, 3)
Data type : int32
Size : 9


In [9]:
a=np.random.randint(10,20,size=(10,20))
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[19 12 12 18 13 14 11 11 18 16 14 16 19 16 14 19 17 14 15 18]
 [19 14 10 15 19 17 10 17 19 15 17 17 13 18 15 11 19 17 15 16]
 [19 17 15 10 13 14 13 12 18 16 11 15 15 16 13 12 10 17 17 17]
 [12 15 16 11 13 12 12 13 12 12 19 16 18 10 12 11 17 18 19 11]
 [10 10 17 19 15 11 11 10 14 17 15 17 17 11 17 17 10 18 14 17]
 [13 12 11 12 16 15 12 17 17 16 16 14 10 18 14 15 12 16 18 19]
 [17 18 15 10 15 13 11 15 18 18 11 18 16 19 10 11 11 19 11 19]
 [19 18 18 12 13 10 16 14 17 10 10 13 13 12 18 14 11 19 13 10]
 [11 15 12 14 12 12 16 14 12 10 15 17 10 13 16 17 15 16 17 14]
 [14 15 14 17 12 12 19 12 10 14 15 15 10 10 11 10 10 10 19 12]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (10, 20)
Data type : int32
Size : 200


In [10]:
a=np.random.randint(10,20,size=(3,3,3))
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[13 17 17]
  [13 12 19]
  [11 13 18]]

 [[17 10 19]
  [10 13 15]
  [10 10 17]]

 [[10 15 12]
  [17 16 19]
  [17 10 17]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (3, 3, 3)
Data type : int32
Size : 27


In [11]:
a=np.random.randint(10,20,size=(3,3,3,3))
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[[13 10 17]
   [10 10 13]
   [16 18 13]]

  [[15 12 15]
   [11 18 10]
   [17 18 11]]

  [[15 19 15]
   [15 12 12]
   [15 13 17]]]


 [[[17 19 14]
   [19 16 19]
   [12 11 10]]

  [[18 12 16]
   [17 10 11]
   [17 13 15]]

  [[12 14 19]
   [14 16 11]
   [17 11 16]]]


 [[[15 12 15]
   [17 19 11]
   [16 14 10]]

  [[19 19 17]
   [11 14 17]
   [10 13 11]]

  [[14 12 15]
   [11 12 15]
   [10 18 19]]]] <class 'numpy.ndarray'>
Dimension : 4
Shape : (3, 3, 3, 3)
Data type : int32
Size : 81


In [12]:
import sys
a=np.random.randint(10,20,size=(3,3),dtype='int16')
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)
print("Capacity of memory",sys.getsizeof(a))

[[19 13 16]
 [16 16 10]
 [18 13 12]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (3, 3)
Data type : int16
Size : 9
Capacity of memory 146


In [13]:
a=np.random.rand()
print(a,type(a))

0.7911620877399028 <class 'float'>


In [14]:
a=np.random.rand(5)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[0.54625205 0.0224486  0.03346801 0.35543242 0.43979363] <class 'numpy.ndarray'>
Dimension : 1
Shape : (5,)
Data type : float64
Size : 5


In [15]:
a=np.random.rand(2,3,3)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[0.12191869 0.50436999 0.08142483]
  [0.39947234 0.37975632 0.14528568]
  [0.13978041 0.40387523 0.96606007]]

 [[0.0100828  0.78054136 0.12707754]
  [0.02388486 0.69329454 0.23401682]
  [0.48235123 0.52934693 0.67118612]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (2, 3, 3)
Data type : float64
Size : 18


In [16]:
a=np.random.uniform()
print(a,type(a))

0.7752936703868593 <class 'float'>


In [17]:
a=np.random.uniform(10)
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

4.886638102836461 <class 'float'>


AttributeError: 'float' object has no attribute 'ndim'

In [22]:
a=np.random.uniform(10,20)
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

10.65832985802644 <class 'float'>


AttributeError: 'float' object has no attribute 'dtype'

In [20]:
a=np.random.uniform(10)
print(a,type(a))

5.8452294695357 <class 'float'>


In [19]:
a=np.random.uniform(1.5,2.5,size=10)
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[2.1106918  1.94652941 2.37225359 2.30959799 1.71653193 2.34487955
 2.49170181 1.68768384 1.75976357 1.91236925] <class 'numpy.ndarray'>
Dimension : 1
Shape : (10,)
Data type : float64
Size : 10


In [23]:
a=np.random.uniform(1.5,2.5,size=(2,3))
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[2.30624047 2.11946062 2.27901029]
 [2.20552515 2.3095045  2.04036514]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (2, 3)
Data type : float64
Size : 6


In [ ]:
a=np.random.uniform(1.5,2.5,size=(3,3,3,3))
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

In [ ]:
#randn()

In [24]:
a=np.random.randn()
print(a,type(a))

1.3237338368212799 <class 'float'>


In [25]:
a=np.random.randn(2,6)
print(a,type(a))

[[-0.22225822 -0.29925912  0.21160648 -0.46767266  0.49760813 -0.53479563]
 [ 0.35983765  0.19173141  1.03970534  1.41883517 -0.00805943  1.64989722]] <class 'numpy.ndarray'>


In [26]:
a=np.random.randn(3,3)
print(a,type(a))

[[-0.33785885 -0.07110797 -0.38485517]
 [ 0.21174017 -0.07356256 -0.98554098]
 [ 0.18754467 -3.17381515 -0.64388277]] <class 'numpy.ndarray'>


In [27]:
a=np.random.randn(5)
print(a,type(a))

[-0.74427955  0.41400226  1.09020482 -1.21547246 -0.37117967] <class 'numpy.ndarray'>


In [28]:
a=np.random.randn(3,3,3)
print(a,type(a))

[[[ 1.28179063e+00  1.20566781e+00 -7.23680674e-01]
  [-1.44949326e-03  8.81577807e-01  7.55729151e-01]
  [ 5.54628915e-01  5.29036736e-01 -1.18272344e+00]]

 [[ 6.46035134e-01 -5.65699552e-01 -1.54734581e+00]
  [ 3.74630583e-01  6.74646096e-01  1.33644935e-01]
  [ 1.85503843e+00 -4.61170460e-01 -1.66617033e-01]]

 [[ 2.03093138e+00 -4.83091749e-01  8.28818730e-01]
  [ 1.02499203e-02  1.53548241e+00  7.98314546e-01]
  [ 1.02994453e+00  8.76560622e-01 -1.27109581e-01]]] <class 'numpy.ndarray'>


In [ ]:
#Normal


In [ ]:
a=np.random.normal()
print(a,type(a))

In [32]:
a=np.random.normal(10,2,size=6)
print(a,type(a))

[11.89475918  9.0657808   8.71673088  9.25163393  7.39943161 10.29264134] <class 'numpy.ndarray'>


In [30]:
a=np.random.normal(10,2,size=(3,3))
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[10.55321584 10.0064787   9.48127109]
 [ 8.04863884 10.2882892  10.86736906]
 [10.40850469  7.79855314 10.66427546]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (3, 3)
Data type : float64
Size : 9


In [ ]:
a=np.random.normal(10,2,size=(3,3,3))
print(a,type(a))
print("Dimension :",a.ndim) 
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

In [ ]:
#Shuffle


In [ ]:
a=np.random.shuffle()
print(a,type(a))

In [ ]:
lst=np.array([10,20,30,40,50,60])
print(lst,type(lst))
a=np.random.shuffle(lst)
print(a,type(a))

In [ ]:
print("Lst =",lst)

In [ ]:
a=np.random.shuffle(lst)
print("Lst =",lst)

In [ ]:
a=np.random.randint(10,100,size=(5,5))
print(a,type(a))

In [ ]:
np.random.shuffle(a)
print(a,type(a))

In [ ]:
np.random.shuffle(a)
print(a,type(a))