In [1]:
import numpy as np

In [5]:
arr1=np.array([10,30,50,60,80])
arr2=np.array([20,40,70,6,3])
newarr=np.add(arr1,arr2)
print(newarr)

[ 30  70 120  66  83]


In [6]:
arr1=np.array([10,30,50,60,80])
arr2=np.array([20,40,70,6,3])
newarr=np.subtract(arr1,arr2)
print(newarr)

[-10 -10 -20  54  77]


In [7]:
arr1=np.array([10,30,50,60,80])
arr2=np.array([20,40,70,6,3])
newarr=np.multiply(arr1,arr2)
print(newarr)

[ 200 1200 3500  360  240]


In [8]:
arr1=np.array([10,30,50,60,80])
arr2=np.array([20,40,70,6,3])
newarr=np.divide(arr1,arr2)
print(newarr)

[ 0.5         0.75        0.71428571 10.         26.66666667]


In [9]:
arr1=np.array([10,30,50,60,80,10])
arr2=np.array([20,40,70,6,3,0])
newarr=np.divide(arr1,arr2)
print(newarr)

[ 0.5         0.75        0.71428571 10.         26.66666667         inf]


C:\Users\dell\AppData\Local\Temp\ipykernel_9888\3526457158.py:3: RuntimeWarning: divide by zero encountered in divide
  newarr=np.divide(arr1,arr2)


In [11]:
na=newarr.astype("str")
print(na)
na[-1]="Can't Devide"
print(na)

['0.5' '0.75' '0.7142857142857143' '10.0' '26.666666666666668' 'inf']
['0.5' '0.75' '0.7142857142857143' '10.0' '26.666666666666668'
 "Can't Devide"]


In [13]:
arr1=np.array([10,30,50,60,80,60])
arr2=np.array([20,40,70,6,3,33])
newarr=np.power(arr1,arr2)
print(newarr)

[7766279631452241920 1696028571681685504                   0
         46656000000              512000                   0]


In [14]:
arr1=np.array([10,30,50,60,80,60])
arr2=np.array([20,40,70,6,3,33])
newarr=np.mod(arr1,arr2)
print(newarr)

[10 30 50  0  2 27]


In [15]:
arr1=np.array([10,30,50,60,80,60])
arr2=np.array([20,40,70,6,3,33])
newarr=np.remainder(arr1,arr2)
print(newarr)

[10 30 50  0  2 27]


In [16]:
# Co

In [17]:
arr1=np.array([10,30,50,60,80,60])
arr2=np.array([20,40,70,6,3,33])
newarr=np.divmod(arr1,arr2)
print(newarr)

(array([ 0,  0,  0, 10, 26,  1]), array([10, 30, 50,  0,  2, 27]))


In [18]:
arr1=np.array([-1,-2,-3,2,-4,-1])
newarr=np.absolute(arr1)
print(newarr)

[1 2 3 2 4 1]


In [19]:
a=np.array(range(-5,5)).reshape(5,2)
print(a)

[[-5 -4]
 [-3 -2]
 [-1  0]
 [ 1  2]
 [ 3  4]]


In [20]:
newarr=np.absolute(a)
print(newarr)

[[5 4]
 [3 2]
 [1 0]
 [1 2]
 [3 4]]


In [21]:
# DIscrete Differences