In [1]:
import numpy as np

In [2]:
a=np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [3]:
a[0:4]

array([0, 1, 2, 3])

In [4]:
a[-16:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# print(a)

In [5]:
a[1:5]

array([1, 2, 3, 4])

In [6]:
a[-1:-5]

array([], dtype=int64)

In [7]:
a[-1:]

array([15])

In [8]:
a[1:-5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a[-1:0]

array([], dtype=int64)

In [10]:
a[-10:-1]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a[-1:-5:-1]

array([15, 14, 13, 12])

In [12]:
a[:-6]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a[-6:]

array([10, 11, 12, 13, 14, 15])

In [14]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
a[1][1]

np.int64(5)

In [ ]:
a[0:3 ]