In [1]:
import numpy as np

In [2]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
b=np.split(a,2)
print(b,type(b))

[array([0, 1, 2]), array([3, 4, 5])] <class 'list'>


In [4]:
a=np.arange(10)
print(a)
print(np.split(a,5))

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [5]:
a=np.arange(12)
print(a)
print(np.split(a,[3,5,6,9,11]))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([ 9, 10]), array([11])]


In [6]:
a=np.arange(12)
print(a)
print(np.split(a,[3,5,6,9,13]))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8]), array([ 9, 10, 11]), array([], dtype=int64)]


In [7]:
a=np.arange(12)
b=np.split(a,5)
print(b)

ValueError: array split does not result in an equal division

In [ ]:
#array_split()

In [ ]:
a=np.arange(12)
b=np.array_split(a,5)
print(b)

In [ ]:
#array_split()
a=np.arange(13)
b=np.array_split(a,[4,5,7,9])
print(b)

In [ ]:
#array_split()
a=np.arange(13)
b=np.array_split(a,[6,12])
print(b)

In [ ]:
#array_split()
a=np.arange(12)
b=np.array_split(a,2)
print(b)

In [ ]:
#splitint 2D array

In [8]:
#splitint 2D array base on Column
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array : \n", a)
#spliting the array into 3 equal along second axis (axis=1)
b=np.split(a,3,axis=1)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Result After split() along with axis=1 
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [9]:
#splitint 2D array base on Row
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array : \n", a)
#spliting the array into 3 equal along second axis (axis=0)
b=np.split(a,3,axis=0)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Result After split() along with axis=1 
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
#Vsplit()

In [10]:
#splitint 2D array base on Row
a=np.arange(12).reshape(4,3)
print("2D Array : \n", a)
#spliting the array into 3 equal along second axis (axis=0)
b=np.vsplit(a,2)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Result After split() along with axis=1 
 [array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]


In [ ]:
#splitint 2D array base on Column
#hsplit()


In [15]:
#splitint 2D array base on Column
a=np.arange(16).reshape(4,4)
print("2D Array : \n", a)
b=np.hsplit(a,2)
print("\n Result After split() along with axis=1 \n",b)
print("-"*50)
print(np.hsplit(a,4))

2D Array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Result After split() along with axis=1 
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
--------------------------------------------------
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [16]:
#splitint 2D array base on Column
a=np.arange(8).reshape(4,2)
print("2D Array : \n", a)
b=np.hsplit(a,2)

print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

 Result After split() along with axis=1 
 [array([[0],
       [2],
       [4],
       [6]]), array([[1],
       [3],
       [5],
       [7]])]


In [ ]:
#dsplit()

In [17]:
#splitint 2D array base on Column
a=np.arange(24).reshape((2,3,4))
print("2D Array : \n", a)
b=np.dsplit(a,2)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 Result After split() along with axis=1 
 [array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [18]:
#splitint 2D array base on Column
a=np.arange(24).reshape((2,3,4))
print("2D Array : \n", a)
b=np.dsplit(a,4)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 Result After split() along with axis=1 
 [array([[[ 0],
        [ 4],
        [ 8]],

       [[12],
        [16],
        [20]]]), array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]]), array([[[ 2],
        [ 6],
        [10]],

       [[14],
        [18],
        [22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]


In [19]:
#splitint 2D array base on Column
a=np.arange(24).reshape((2,4,3))
print("2D Array : \n", a)
b=np.dsplit(a,3)
print("\n Result After split() along with axis=1 \n",b)

2D Array : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

 Result After split() along with axis=1 
 [array([[[ 0],
        [ 3],
        [ 6],
        [ 9]],

       [[12],
        [15],
        [18],
        [21]]]), array([[[ 1],
        [ 4],
        [ 7],
        [10]],

       [[13],
        [16],
        [19],
        [22]]]), array([[[ 2],
        [ 5],
        [ 8],
        [11]],

       [[14],
        [17],
        [20],
        [23]]])]
