In [1]:
import numpy as np

In [2]:
# MIN MAX

In [3]:
# 1D Array 

In [4]:
a=np.array([10,20,-3,45,-89,365,0,25,46,-5])
print(a)

[ 10  20  -3  45 -89 365   0  25  46  -5]


In [5]:
# 1D Array
a=np.array([10,20,-3,45,-89,365,0,25,46,-5])
print(a)
print("-"*50)
maxv=np.amax(a)
minv=np.amin(a)
print("Max Val = ",maxv)
print("Min Val = ",minv)

[ 10  20  -3  45 -89 365   0  25  46  -5]
--------------------------------------------------
Max Val =  365
Min Val =  -89


In [6]:
 # 2D Array
a=np.array([[10,20,-3,45,-89],[365,0,25,46,-5],[564,-287,43,45,659],[385,0,25,596,-5000]])
print(a)
print("-"*20,"Max","-"*20)
colmax=np.amax(a,axis=0)
rowmax=np.amax(a,axis=1)
print("Max Val = ",colmax)
print("Min Val = ",rowmax)
print("-"*20,"Min","-"*20)
colmin=np.amin(a,axis=0)
rowmin=np.amin(a,axis=1)
print("Max Val = ",colmin)
print("Min Val = ",rowmin)

[[   10    20    -3    45   -89]
 [  365     0    25    46    -5]
 [  564  -287    43    45   659]
 [  385     0    25   596 -5000]]
-------------------- Max --------------------
Max Val =  [564  20  43 596 659]
Min Val =  [ 45 365 659 596]
-------------------- Min --------------------
Max Val =  [   10  -287    -3    45 -5000]
Min Val =  [  -89    -5  -287 -5000]


In [7]:
# Findin Mean

In [8]:
# 1D
a=np.array([20,20,30,40,50,10])
print("Content of a\n",a)
print("-"*50)
mv=np.mean(a)
print("Mean of a=",mv)
print("-"*50)

Content of a
 [20 20 30 40 50 10]
--------------------------------------------------
Mean of a= 28.333333333333332
--------------------------------------------------


In [9]:
 # 2D Array
a=np.array([[10,20,-3,45,-89],[365,0,25,46,-5],[564,-287,43,45,659],[385,0,25,596,-5000]])
print(a)
print("-"*20,"MEAN","-"*20)
mv=np.mean(a)
print("Mean of a=",mv)
print("-"*50)


[[   10    20    -3    45   -89]
 [  365     0    25    46    -5]
 [  564  -287    43    45   659]
 [  385     0    25   596 -5000]]
-------------------- MEAN --------------------
Mean of a= -127.8
--------------------------------------------------


In [10]:
 # 2D Array
a=np.array([[10,20,-3,45,-89],[365,0,25,46,-5],[564,-287,43,45,659],[385,0,25,596,-5000]])
print(a)
print("-"*20,"MEAN","-"*20)
colmean=np.mean(a,axis=0)
rowmean=np.mean (a,axis=1)
print("Column Mean Val = ",colmean)
print("Row Mean Val = ",rowmean)
print("-"*50)

[[   10    20    -3    45   -89]
 [  365     0    25    46    -5]
 [  564  -287    43    45   659]
 [  385     0    25   596 -5000]]
-------------------- MEAN --------------------
Column Mean Val =  [  331.     -66.75    22.5    183.   -1108.75]
Row Mean Val =  [  -3.4   86.2  204.8 -798.8]
--------------------------------------------------


In [11]:
# Meadian

In [12]:
s=np.array([12,35,24,6,36,8,9])
print(s)
print("-"*50)
med=np.median(s)
print("Median =",med)
print("-"*50)

[12 35 24  6 36  8  9]
--------------------------------------------------
Median = 12.0
--------------------------------------------------


In [13]:
s=np.array([12,35,24,6,36,8,9,2])
print(s)
print("-"*50)
med=np.median(s)
print("Median =",med)
print("-"*50)

[12 35 24  6 36  8  9  2]
--------------------------------------------------
Median = 10.5
--------------------------------------------------


In [14]:
 # 2D Array
a=np.array([[10,20,30],[2,15,95],[36,14,5]])
print(a)
print("-"*20,"MEDIAN","-"*20)
smedian=np.median(a)
print("Median Val = ",smedian)
print("-"*50)

[[10 20 30]
 [ 2 15 95]
 [36 14  5]]
-------------------- MEDIAN --------------------
Median Val =  15.0
--------------------------------------------------


In [15]:
 # 2D Array
a=np.array([[10,20,30],[2,15,95],[36,14,5]])
print(a)
print("-"*20,"MEDIAN","-"*20)
colmedian=np.median(a,axis=0)
rowmedian=np.median(a,axis=1)
print("Column Median Val = ",colmedian)
print("Row Median Val = ",rowmedian)
print("-"*50)

[[10 20 30]
 [ 2 15 95]
 [36 14  5]]
-------------------- MEDIAN --------------------
Column Median Val =  [10. 15. 30.]
Row Median Val =  [20. 15. 14.]
--------------------------------------------------


In [16]:
# Variance

In [18]:
 # 2D Array
a=np.array([[2,4],[1,3]])
print(a)
print("-"*20,"Varance","-"*20)
cVarance=np.var(a)
print("Varance Val = ",cVarance)
print("-"*50)

[[2 4]
 [1 3]]
-------------------- Varance --------------------
Varance Val =  1.25
--------------------------------------------------


In [20]:
 # 2D Array
a=np.array([[10,20,30],[2,15,95],[36,14,5]])
print(a)
print("-"*20,"Varance","-"*20)
colVarance=np.var(a,axis=0)
rowVarance=np.var(a,axis=1)
cVarance=np.var(a)
print("Varance Val = ",cVarance)
print("-"*50)
print("Column Varance Val = ",colVarance)
print("Row VaranceVal = ",rowVarance)
print("-"*50)

[[10 20 30]
 [ 2 15 95]
 [36 14  5]]
-------------------- Varance --------------------
Varance Val =  716.1728395061729
--------------------------------------------------
Column Varance Val =  [ 210.66666667    6.88888889 1438.88888889]
Row VaranceVal =  [  66.66666667 1690.88888889  169.55555556]
--------------------------------------------------


In [21]:
 # 2D Array
a=np.array([[2,4],[1,3]])
print(a)
print("-"*20,"Varance","-"*20)
colVarance=np.var(a,axis=0)
rowVarance=np.var(a,axis=1)
cVarance=np.var(a)
print("Varance Val = ",cVarance)
print("-"*50)
print("Column Varance Val = ",colVarance)
print("Row VaranceVal = ",rowVarance)
print("-"*50)

[[2 4]
 [1 3]]
-------------------- Varance --------------------
Varance Val =  1.25
--------------------------------------------------
Column Varance Val =  [0.25 0.25]
Row VaranceVal =  [1. 1.]
--------------------------------------------------


In [22]:
# Stander Deviation

In [23]:
 # 2D Array
a=np.array([[2,4],[1,3]])
print(a)
print("-"*20,"Stander Deviation","-"*20)
colstd=np.std(a,axis=0)
rowstd=np.std(a,axis=1)
cstd=np.std(a)
print("Stander Deviation Val = ",cstd)
print("-"*50)
print("Column Stander Deviation Val = ",colstd)
print("Row Stander Deviation Val = ",rowstd)
print("-"*50)

[[2 4]
 [1 3]]
-------------------- Stander Deviation --------------------
Stander Deviation Val =  1.118033988749895
--------------------------------------------------
Column Stander Deviation Val =  [0.5 0.5]
Row Stander Deviation Val =  [1. 1.]
--------------------------------------------------


In [25]:
import statistics as s

In [27]:
lst=[10,20,30,40,10,30,50,20,10,15]
a=np.array(lst)
val=s.mode(a)
print(val)

10


In [28]:
lst=[10,20,30,40,10,30,50,20,10,15,20,30]
a=np.array(lst)
val=s.mode(a)
print(val)

10


In [29]:
# MultiMode

In [36]:
lst=[10,20,30,40,10,30,50,20,10,15,20,30]
a=np.array(lst)
val=s.multimode(a)
print(val)

[np.int64(10), np.int64(20), np.int64(30)]
