In [1]:
import numpy as np

In [2]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [3]:
tr=np.trace(a)

In [4]:
print(tr)

150


In [12]:
a=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)
tr=np.trace(a)
print("Traace=",tr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
Traace= 3


In [14]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
x=a[(0,1,2),(2,1,0)]
print(x)

[30 50 70]


In [16]:
np.sum(x)

np.int64(150)

In [17]:
a=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [18]:
a.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Orignal Matrix\n",a)
print("Transpos of Matrix\n",a.T)

Orignal Matrix
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Transpos of Matrix
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [21]:
a=np.array([[10,20,30],[40,50,60]])
print("Orignal Matrix\n",a)
print("Shape of A=",a.shape)
print("="*50)
at=a.T
print("Transpos of Matrix\n",at)
print("Shape of Transpos Matric=",at.shape)
print("="*50)

Orignal Matrix
 [[10 20 30]
 [40 50 60]]
Shape of A= (2, 3)
Transpos of Matrix
 [[10 40]
 [20 50]
 [30 60]]
Shape of Transpos Matric= (3, 2)


In [22]:
a=np.array([[10,20,30],[40,50,60]])
print("Orignal Matrix\n",a)
print("Shape of A=",a.shape)
print("="*50)
at=np.transpose(a)
print("Transpos of Matrix\n",at)
print("Shape of Transpos Matric=",at.shape)
print("="*50)

Orignal Matrix
 [[10 20 30]
 [40 50 60]]
Shape of A= (2, 3)
Transpos of Matrix
 [[10 40]
 [20 50]
 [30 60]]
Shape of Transpos Matric= (3, 2)


In [23]:
# Inner ()of numpy

In [25]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,22],[13,14]])
print("Matrix A\n",a)
print("Matrix B\n",b)

Matrix A
 [[1 2]
 [3 4]]
Matrix B
 [[11 22]
 [13 14]]


In [26]:
c=np.dot(a,b)
print(c)

[[ 37  50]
 [ 85 122]]


In [27]:
c=np.dot(b,a)
print(c)

[[ 77 110]
 [ 55  82]]


In [28]:
c=np.multiply(a,b)
print(c)

[[11 44]
 [39 56]]


In [29]:
c=np.multiply(b,a)
print(c)

[[11 44]
 [39 56]]


In [33]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print("Matrix A\n",a)
print("Matrix B\n",b)
k=np.inner(a,b)
print("Inner Product Mtrix-A and Matix-B\n",k)

Matrix A
 [[1 2]
 [3 4]]
Matrix B
 [[11 12]
 [13 14]]
Inner Product Mtrix-A and Matix-B
 [[35 41]
 [81 95]]


In [34]:
a=np.array([1,2,3,4])
b=np.array([11,12,13,14])
print("Matrix A\n",a)
print("Matrix B\n",b)
k=np.dot(a,b)
print("Multiplication of 1-D Arrays with Dot Mtrix-A and Matix-B\n",k)

Matrix A
 [1 2 3 4]
Matrix B
 [11 12 13 14]
Multiplication of 1-D Arrays with Dot Mtrix-A and Matix-B
 130


In [ ]:
# Outer

In [39]:
a=np.array([1,2,3,4])
b=np.array([11,12,13,14])
print("Matrix A\n",a)
print("Matrix B\n",b)
k=np.outer(a,b)
print("Outer Product Multiplication\n",k)

Matrix A
 [1 2 3 4]
Matrix B
 [11 12 13 14]
Outer Product Multiplication
 [[11 12 13 14]
 [22 24 26 28]
 [33 36 39 42]
 [44 48 52 56]]


In [40]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print("Matrix A\n",a)
print("Matrix B\n",b)
k=np.outer(a,b)
print("Outer Product Multiplication\n",k)

Matrix A
 [[1 2]
 [3 4]]
Matrix B
 [[11 12]
 [13 14]]
Outer Product Multiplication
 [[11 12 13 14]
 [22 24 26 28]
 [33 36 39 42]
 [44 48 52 56]]


In [41]:
# Find Rank of Matrix

In [44]:
a=np.array([[2,4],[4,8]])
print("matrix A\n",a)
rnk=np.linalg.matrix_rank(a)
print("Rank of A =",rnk)

matrix A
 [[2 4]
 [4 8]]
Rank of A = 1


In [45]:
a=np.array([[2,4],[3,5]])
print("matrix A\n",a)
rnk=np.linalg.matrix_rank(a)
print("Rank of A =",rnk)

matrix A
 [[2 4]
 [3 5]]
Rank of A = 2


In [46]:
a=np.array([[1,0,0],[0,1,0],[0,0,1]])
print("matrix A\n",a)
rnk=np.linalg.matrix_rank(a)
print("Rank of A =",rnk)

matrix A
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Rank of A = 3
