In [1]:
import numpy as np

In [2]:
a=np.array([10,20,30,40,20,10,60,40,20,30])
print(a,type(a))

[10 20 30 40 20 10 60 40 20 30] <class 'numpy.ndarray'>


In [3]:
sa=np.unique(a)
print(sa,type(sa))

[10 20 30 40 60] <class 'numpy.ndarray'>


In [4]:
a=np.array([10,20,30,40,20,10,60,40,20,30,20,10]).reshape(3,4)
print(a,type(a))

[[10 20 30 40]
 [20 10 60 40]
 [20 30 20 10]] <class 'numpy.ndarray'>


In [5]:
sa=np.unique(a)
print(sa,type(sa))

[10 20 30 40 60] <class 'numpy.ndarray'>


In [6]:
a=np.array([10,20,30,40,20,10,60,40,20,30,15])
print("Contend OF A =",a)
print("="*50)
sa,ind=np.unique(a,return_index=True)
print("Unique Elements=",sa)
print("Indices Of Unique Elements=",ind)

Contend OF A = [10 20 30 40 20 10 60 40 20 30 15]
Unique Elements= [10 15 20 30 40 60]
Indices Of Unique Elements= [ 0 10  1  2  3  6]


In [7]:
a=np.array([10,20,30,40,20,10,60,40,20,30,20,10]).reshape(3,4)
print("Contend OF A =",a)
print("="*50)
sa,ind=np.unique(a,return_index=True)
print("Unique Elements=",sa)
print("Indices Of Unique Elements=",ind)

Contend OF A = [[10 20 30 40]
 [20 10 60 40]
 [20 30 20 10]]
Unique Elements= [10 20 30 40 60]
Indices Of Unique Elements= [0 1 2 3 6]


In [8]:
a=np.array([10,20,30,40,20,10,60,40,20,30,15])
print("Contend OF A =",a)
print("="*50)
sa,ind=np.unique(a,return_inverse=True)
print("Unique Elements=",sa)
print("Indices Of Unique Elements=",ind)

Contend OF A = [10 20 30 40 20 10 60 40 20 30 15]
Unique Elements= [10 15 20 30 40 60]
Indices Of Unique Elements= [0 2 3 4 2 0 5 4 2 3 1]


In [9]:
a=np.array([10,20,30,40,20,10,60,40,20,30,15])
print("Contend OF A =",a)
print("="*50)
sa,ind=np.unique(a,return_counts=True)
print("Unique Elements=",sa)
print("Indices Of Unique Elements=",ind)

Contend OF A = [10 20 30 40 20 10 60 40 20 30 15]
Unique Elements= [10 15 20 30 40 60]
Indices Of Unique Elements= [2 1 3 2 2 1]


In [10]:
# Union

In [11]:
a=np.array([10,20,30,40])
b=np.array([1,2,10,20])
c=np.union1d(a,b)
print(c)

[ 1  2 10 20 30 40]


In [12]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[10,20]])
c=np.union1d(a,b)
print(c)

[ 1  2 10 20 30 40]


In [13]:
# Intercsection

In [14]:
a=np.array([10,20,30,40])
b=np.array([1,2,10,20])
c=np.intersect1d(a,b)
print(c)

[10 20]


In [15]:
a=np.array([[10,20],[30,40]])
b=np.array([[1,2],[10,20]])
c=np.intersect1d(a,b)
print(c)

[10 20]


In [27]:
# Finding set Differance

In [26]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setdiff1d(a,b)
print(c)

[10 20]


In [24]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setdiff1d(a,b,assume_unique=True)
print(c)

[10 20]


In [28]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setdiff1d(b,a)
print(c)

[50 60]


In [29]:
# Finding Symmetric Difference

In [30]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setxor1d(a,b)
print(c)

[10 20 50 60]


In [31]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setxor1d(a,b,assume_unique=True)
print(c)

[10 20 50 60]


In [32]:
a=np.array([10,20,30,40])
b=np.array([30,40,50,60])
c=np.setxor1d(b,a)
print(c)

[10 20 50 60]
