In [1]:
import numpy as np

In [2]:
b=100
a=np.array(b)

In [3]:
print(a,type(a))

100 <class 'numpy.ndarray'>


In [4]:
a

array(100)

In [5]:
print(a.ndim)

0


In [6]:
a

array(100)

In [7]:
print(a.shape)

()


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
print(a.size)

1


In [10]:
print(a.dtype)

int64


In [11]:
x=10
print(x,type(x))

10 <class 'int'>


In [12]:
a=np.array(x)
print(a,type(a))

10 <class 'numpy.ndarray'>


In [13]:
a

array(10)

In [14]:
a.ndim

0

In [15]:
a.shape

()

In [16]:
x=[10]
print(x,type(x))

[10] <class 'list'>


In [17]:
a=np.array(x)
print(a,type(a))
a
a.ndim
a.shape

[10] <class 'numpy.ndarray'>


(1,)

In [18]:
r=range(10,25)
print(r,type(r))
print("-"*50)
a=np.array(r)
print(a,type(a),len(a))

range(10, 25) <class 'range'>
--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <class 'numpy.ndarray'> 15


In [19]:
a.ndim
a.shape

(15,)

In [20]:
a.shape
a.shape=(3,5)

In [21]:
print(a,type(a))

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] <class 'numpy.ndarray'>


In [22]:
a.ndim

2

In [23]:
a.shape

(3, 5)

In [24]:
a.ndim

2

In [25]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
a.dtype

dtype('int64')

In [27]:
r=range(10,25)
a=np.array(r,dtype=float)
print(a,type(a),len(a),a.dtype)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.] <class 'numpy.ndarray'> 15 float64


In [28]:
r=range(10,25)
a=np.array(r, )
print(a,type(a),len(a),a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <class 'numpy.ndarray'> 15 int64


In [29]:
a.dtype

dtype('int64')

In [30]:
lst=[10,20,30,40,50,60]
print(lst)
a=np.array(lst)
print(a,type(a))
print("-"*50)
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)

[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60] <class 'numpy.ndarray'>
--------------------------------------------------
Dimension : 1
Shape : (6,)
Data type : int64


In [31]:
lst=[[10,20,30],[40,50,60],[80,90,100]]
print(lst)
a=np.array(lst)
print(a,type(a))
print("-"*50)
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)

[[10, 20, 30], [40, 50, 60], [80, 90, 100]]
[[ 10  20  30]
 [ 40  50  60]
 [ 80  90 100]] <class 'numpy.ndarray'>
--------------------------------------------------
Dimension : 2
Shape : (3, 3)
Data type : int64


In [32]:
lst=[[[10,20,30],[40,50,60]],[[1,20,3],[20,60,9]]]
print(lst)
a=np.array(lst)
print(a,type(a))
print("-"*50)
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)

[[[10, 20, 30], [40, 50, 60]], [[1, 20, 3], [20, 60, 9]]]
[[[10 20 30]
  [40 50 60]]

 [[ 1 20  3]
  [20 60  9]]] <class 'numpy.ndarray'>
--------------------------------------------------
Dimension : 3
Shape : (2, 2, 3)
Data type : int64


In [33]:
a.shape

(2, 2, 3)

In [34]:
a.shape=(2,2,3)
print(a)
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)

[[[10 20 30]
  [40 50 60]]

 [[ 1 20  3]
  [20 60  9]]]
Dimension : 3
Shape : (2, 2, 3)
Data type : int64


In [35]:
r=range(1,33)
a=np.array(r)
a.shape=(2,2,2,2,2)
print(a)
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)

[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[17 18]
    [19 20]]

   [[21 22]
    [23 24]]]


  [[[25 26]
    [27 28]]

   [[29 30]
    [31 32]]]]]
Dimension : 5
Shape : (2, 2, 2, 2, 2)
Data type : int64


In [36]:
dic={10:"Apple",20:"Mango",30:"Kiwi",40:"Guava"}
print(dic,type(dic))

{10: 'Apple', 20: 'Mango', 30: 'Kiwi', 40: 'Guava'} <class 'dict'>


In [60]:
a=np.array(dic)
a
print("-"*50)

--------------------------------------------------


In [38]:
a

array({10: 'Apple', 20: 'Mango', 30: 'Kiwi', 40: 'Guava'}, dtype=object)

In [47]:
print(a,type(a))
print(a.ndim,"\t",a.dtype,"\t",a.shape)
print(a.size)


{10: 'Apple', 20: 'Mango', 30: 'Kiwi', 40: 'Guava'} <class 'numpy.ndarray'>
0 	 object 	 ()
1


In [63]:
a=np.arange(0,12,dtype=float)
print(a)
a

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [65]:
a.shape=(4,3)
print(a)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
