In [43]:
import numpy as np

In [3]:
a=np.zeros(4)
print(a,type(a))

[0. 0. 0. 0.] <class 'numpy.ndarray'>


In [4]:
a=np.zeros(4,dtype=int)
print(a,type(a))

[0 0 0 0] <class 'numpy.ndarray'>


In [9]:
a=np.zeros(16,dtype=int).reshape(2,2,4)
print(a,type(a))

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]] <class 'numpy.ndarray'>


In [12]:
a=np.zeros((2,2,5),dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (2, 2, 5)
Data type : int64
Size : 20


In [13]:
a=np.zeros((2,2,3,4),dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]] <class 'numpy.ndarray'>
Dimension : 4
Shape : (2, 2, 3, 4)
Data type : int64
Size : 48


In [15]:
a=np.ones(10)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
Dimension : 1
Shape : (10,)
Data type : float64
Size : 10


In [16]:
a=np.ones((2,2,5),dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (2, 2, 5)
Data type : int64
Size : 20


In [17]:
a=np.full(4,9)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[9 9 9 9] <class 'numpy.ndarray'>
Dimension : 1
Shape : (4,)
Data type : int64
Size : 4


In [18]:
a=np.full(4,9).reshape(2,2)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[9 9]
 [9 9]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (2, 2)
Data type : int64
Size : 4


In [19]:
a=np.full((2,3),6)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[6 6 6]
 [6 6 6]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (2, 3)
Data type : int64
Size : 6


In [20]:
a=np.full((3,3,3),9)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]] <class 'numpy.ndarray'>
Dimension : 3
Shape : (3, 3, 3)
Data type : int64
Size : 27


In [21]:
a=np.full((3,3),"AKA")
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[['AKA' 'AKA' 'AKA']
 ['AKA' 'AKA' 'AKA']
 ['AKA' 'AKA' 'AKA']] <class 'numpy.ndarray'>
Dimension : 2
Shape : (3, 3)
Data type : <U3
Size : 9


In [25]:
a=np.identity(4)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (4, 4)
Data type : float64
Size : 16


In [27]:
a=np.identity(4,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (4, 4)
Data type : int64
Size : 16


In [29]:
a=np.eye(4,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (4, 4)
Data type : int64
Size : 16


In [30]:
a=np.eye(4,k=-1,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (4, 4)
Data type : int64
Size : 16


In [31]:
a=np.eye(5,k=2,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (5, 5)
Data type : int64
Size : 25


In [34]:
a=np.eye(5,3,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (5, 3)
Data type : int64
Size : 15


In [35]:
a=np.eye(5,3,k=-1,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (5, 3)
Data type : int64
Size : 15


In [42]:
a=np.eye(10,10,k=4,dtype=int)
print(a,type(a))
print("Dimension :",a.ndim)
print("Shape :",a.shape)
print("Data type :",a.dtype)
print("Size :",a.size)

[[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] <class 'numpy.ndarray'>
Dimension : 2
Shape : (10, 10)
Data type : int64
Size : 100
